### PR TITLE
Converted to Template for dynamic content

### PR DESCRIPTION
**Pull request by dark-1**
The dynamic HTML content for enabling/disabling forum notifications
was converted to Template styled
Dynamic Template Row content for enabling/disabling forum notifications

### CODE REVIEW

**Comment by rootslinux** [comment]
What is the motivation for these changes and what do they fix or improve? Is this just an alternative means of doing the same thing? Is it faster or better in some way? (I'm a novice with PHP so keep that in mind). Thanks. (Also just FYI, I'm about to leave on a two week vacation so I might not be able to merge this until after I return).

**Comment by dark-1** [comment]
> What is the motivation for these changes and what do they fix or improve? Is this just an alternative means of doing the same thing? Is it faster or better in some way? (I'm a novice with PHP so keep that in mind). Thanks. (Also just FYI, I'm about to leave on a two week vacation so I might not be able to merge this until after I return).

This is an alternative method.
BUT,
This method is acceptable by phpBB validation team,
your method is not wrong, but will not be acceptable.
they prefer PHP code in `.php` & HTML in `.html`(template file).

Best regards 👍

**Comment by dark-1** [comment]
@rootslinux ,

Do you need more granularity on each forum bases?
like : 
Forum_1 | `master_yes_no`  `post`  `topic`
Forum_2 | `master_yes_no`  `post`  `topic`
If yes, then this will be in another PR.

BR 👍

**Comment by rootslinux** [comment]
Ah, I see. That makes sense and now I remember reading that when I first looked at the contributor guide. Alright, thanks! I didn't even know you could do that templating logic in the html. Did you read my comment about the L_NO_FORUMS label? If this is some label native within PHPBB itself then it's fine, but if its something you needed to define in the language file then we'll need to add that. I'll accept your PR as soon as I know the answer to that.

In response to your comment about the granularity, the answer is no. Forums are either enabled or disabled, and there is no way to enable only topic or post type notifications for a specific forum.

**Comment by dark-1** [comment]
> Ah, I see. That makes sense and now I remember reading that when I first looked at the contributor guide. Alright, thanks! I didn't even know you could do that templating logic in the html. Did you read my comment about the L_NO_FORUMS label? If this is some label native within PHPBB itself then it's fine, but if its something you needed to define in the language file then we'll need to add that. I'll accept your PR as soon as I know the answer to that.
> 
> In response to your comment about the granularity, the answer is no. Forums are either enabled or disabled, and there is no way to enable only topic or post type notifications for a specific forum.

About `L_NO_FORUMS` label , yea! it's native , here : https://github.com/phpbb/phpbb/blob/master/phpBB/language/en/common.php#L517
&
about granularity, `post` will take into account for above master controls like Post create, delete, edit, lock, unlock ... similarly for `topic` .
OR
I can create for all the options from https://github.com/rootslinux/phpbb-discord-notifications/blob/master/adm/style/acp_discord_notifications.html#L43 to https://github.com/rootslinux/phpbb-discord-notifications/blob/master/adm/style/acp_discord_notifications.html#L102 ,
for each forum, actually this was my first idea.

**Comment by rootslinux** [comment]
Okay, I'll go ahead and merge this in then.

Lets hold off on the granularity idea for now. We'd need to do more than simply add all these inputs on the ACP, as the logic in the event listener would need to figure out which notification types are set for which forums, which adds complexity and will require a few changes and a lot of testing. Plus, I don't think there is much for users to gain with this (why would you want a forum to be notified about posts updates but not new topics, and another forum to only be notified about deletes?). Maybe in a future release we can add more granularity, but only if it is a feature that users actually request.

**Comment by dark-1** [comment]
> Okay, I'll go ahead and merge this in then.
> 
> Lets hold off on the granularity idea for now. We'd need to do more than simply add all these inputs on the ACP, as the logic in the event listener would need to figure out which notification types are set for which forums, which adds complexity and will require a few changes and a lot of testing. Plus, I don't think there is much for users to gain with this (why would you want a forum to be notified about posts updates but not new topics, and another forum to only be notified about deletes?). Maybe in a future release we can add more granularity, but only if it is a feature that users actually request.

Yea!! no problem. 
It was actually a feature request by my friend for his forum.
So I thought `why not share it!!!` , hence asked.
Anyway I'll be implementing it , when i get time.

BR friend 👍

**Pull request merged**
